### ISSUE TITLE
Any idea what this means and how to fix?

### ISSUE THREAD

**Issue by EmptikBest** [Torom/BotLi#100]
I was just running my bot and got this:
`ERROR:asyncio:Exception in callback Protocol._line_received('info depth 4...8e6 f5e5 e6f8')
handle: <Handle Protocol._line_received('info depth 4...8e6 f5e5 e6f8')>
Traceback (most recent call last):
  File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 1054, in _line_received
    self.command._line_received(self, line)
  File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 1303, in _line_received
    assert self.state in [CommandState.ACTIVE, CommandState.CANCELLING]`

Any idea what it means and how to fix it?

**Comment by Torom** [comment]
Same as #95
