### ISSUE TITLE
No idea why the bot keeps losing

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#113]
Hey @Torom 

After some lichess explorer moves, the bot keeps failing in evaluations like this

```
2023-07-02T08:01:53.106469+00:00 app[worker.1]: ERROR:chess.engine:Exception parsing pv from info: 'depth 1 seldepth 1 multipv 1 score cp -975 nodes 52 nps 52000 hashfull 0 tbhits 0 time 1 pv c7d6', position at root: r1bpkb1r/ppp1nppp/2n5/1N1pp3/3P4/5N2/PP2PPPP/R1BQKB1R w KQkq - 0 8
2023-07-02T08:01:53.106869+00:00 app[worker.1]: ERROR:chess.engine:Exception parsing pv from info: 'depth 2 seldepth 2 multipv 1 score cp -975 nodes 95 nps 95000 hashfull 0 tbhits 0 time 1 pv c7d6 b5d6 e8d7', position at root: r1bpkb1r/ppp1nppp/2n5/1N1pp3/3P4/5N2/PP2PPPP/R1BQKB1R w KQkq - 0 8
2023-07-02T08:01:53.107247+00:00 app[worker.1]: ERROR:chess.engine:Exception parsing pv from info: 'depth 3 seldepth 3 multipv 1 score cp -975 nodes 138 nps 138000 hashfull 0 tbhits 0 time 1 pv c7d6 b5d6 e8d7', position at root: r1bpkb1r/ppp1nppp/2n5/1N1pp3/3P4/5N2/PP2PPPP/R1BQKB1R w KQkq - 0 8
2023-07-02T08:01:53.107570+00:00 app[worker.1]: ERROR:chess.engine:Exception parsing pv from info: 'depth 4 seldepth 4 multipv 1 score cp -971 nodes 177 nps 177000 hashfull 0 tbhits 0 time 1 pv c7d6 b5d6 e8d7 d4e5 e7g6', position at root: r1bpkb1r/ppp1nppp/2n5/1N1pp3/3P4/5N2/PP2PPPP/R1BQKB1R w KQkq - 0 8
2023-07-02T08:01:53.107882+00:00 app[worker.1]: ERROR:chess.engine:Exception parsing pv from info: 'depth 5 seldepth 5 multipv 1 score cp -971 nodes 217 nps 217000 hashfull 0 tbhits 0 time 1 pv c7d6 b5d6 e8d7 d4e5 e7g6', position at root: r1bpkb1r/ppp1nppp/2n5/1N1pp3/3P4/5N2/PP2PPPP/R1BQKB1R w KQkq - 0 8
2023-07-02T08:01:53.108197+00:00 app[worker.1]: ERROR:chess.engine:Exception parsing pv from info: 'depth 6 seldepth 6 multipv 1 score cp -971 nodes 285 nps 285000 hashfull 0 tbhits 0 time 1 pv c7d6 b5d6 e8d7 d4e5 e7g6 e2e4', position at root: r1bpkb1r/ppp1nppp/2n5/1N1pp3/3P4/5N2/PP2PPPP/R1BQKB1R w KQkq - 0 8
2023-07-02T08:01:53.108506+00:00 app[worker.1]: ERROR:chess.engine:Exception parsing pv from info: 'depth 7 seldepth 8 multipv 1 score cp -971 nodes 347 nps 347000 hashfull 0 tbhits 0 time 1 pv c7d6 b5d6 e8d7 d4e5 e7g6 e2e4 f8d6 e5d6', position at root: r1bpkb1r/ppp1nppp/2n5/1N1pp3/3P4/5N2/PP2PPPP/R1BQKB1R w KQkq - 0 8
2023-07-02T08:01:53.108826+00:00 app[worker.1]: ERROR:chess.engine:Exception parsing pv from info: 'depth 8 seldepth 10 multipv 1 score cp -971 nodes 420 nps 420000 hashfull 0 tbhits 0 time 1 pv c7d6 b5d6 e8d7 d4e5 e7g6 e2e4 f8d6 e5d6 d7d6 d1d5 d6e7', position at root: r1bpkb1r/ppp1nppp/2n5/1N1pp3/3P4/5N2/PP2PPPP/R1BQKB1R w KQkq - 0 8
2023-07-02T08:01:53.109134+00:00 app[worker.1]: ERROR:chess.engine:Exception parsing pv from info: 'depth 9 seldepth 12 multipv 1 score cp -971 nodes 522 nps 522000 hashfull 0 tbhits 0 time 1 pv c7d6 b5d6 e8d7 d4e5 e7g6 e2e4 f8d6 e5d6 d7d6 d1d5 d6e7 f3g5', position at root: r1bpkb1r/ppp1nppp/2n5/1N1pp3/3P4/5N2/PP2PPPP/R1BQKB1R w KQkq - 0 8
2023-07-02T08:01:53.109499+00:00 app[worker.1]: ERROR:chess.engine:Exception parsing pv from info: 'depth 10 seldepth 14 multipv 1 score cp -970 nodes 1036 nps 1036000 hashfull 0 tbhits 0 time 1 pv c7d6 b5d6 e8d7 d4e5 e7g6 e2e4 f8d6 e5d6 d7d6 d1d5 d6e7 f3g5 c8e6 g5e6', position at root: r1bpkb1r/ppp1nppp/2n5/1N1pp3/3P4/5N2/PP2PPPP/R1BQKB1R w KQkq - 0 8
2023-07-02T08:01:53.109807+00:00 app[worker.1]: ERROR:chess.engine:Exception parsing pv from info: 'depth 11 seldepth 16 multipv 1 score cp -970 nodes 1599 nps 799500 hashfull 0 tbhits 0 time 2 pv c7d6 b5d6 e8d7 d4e5 e7g6 e2e4 f8d6 e5d6 d7d6 d1d5 d6e7 f3g5 c8e6 g5e6 f7e6', position at root: r1bpkb1r/ppp1nppp/2n5/1N1pp3/3P4/5N2/PP2PPPP/R1BQKB1R w KQkq - 0 8
2023-07-02T08:01:53.110115+00:00 app[worker.1]: ERROR:chess.engine:Exception parsing pv from info: 'depth 12 seldepth 15 multipv 1 score cp -970 nodes 2047 nps 1023500 hashfull 0 tbhits 0 time 2 pv c7d6 b5d6 e8d7 d4e5 e7g6 e2e4 f8d6 e5d6 d7d6 d1d5 d6e7 f3g5 c8e6 g5e6 f7e6', position at root: r1bpkb1r/ppp1nppp/2n5/1N1pp3/3P4/5N2/PP2PPPP/R1BQKB1R w KQkq - 0 8
2023-07-02T08:01:53.110491+00:00 app[worker.1]: ERROR:chess.engine:Exception parsing pv from info: 'depth 13 seldepth 17 multipv 1 score cp -970 nodes 3672 nps 1224000 hashfull 0 tbhits 0 time 3 pv c7d6 b5d6 e8d7 d4e5 e7g6 e2e4 f8d6 e5d6 d7d6 d1d5 d6e7 f3g5 c8e6 g5e6 f7e6', position at root: r1bpkb1r/ppp1nppp/2n5/1N1pp3/3P4/5N2/PP2PPPP/R1BQKB1R w KQkq - 0 8
2023-07-02T08:01:53.126156+00:00 app[worker.1]: ERROR:chess.engine:Exception parsing pv from info: 'depth 14 seldepth 31 multipv 1 score cp -975 nodes 52961 nps 2648050 hashfull 3 tbhits 0 time 20 pv c7d6 b5d6 e8d7 d4e5 e7g6 d6f7 f8b4 c1d2 h8f8 e5e6 d7e6 f7g5 e6d6 d2b4 c6b4 a1c1 c8f5 d1b3 b4c2 c1c2 f5c2 b3b4 d6c7', position at root: r1bpkb1r/ppp1nppp/2n5/1N1pp3/3P4/5N2/PP2PPPP/R1BQKB1R w KQkq - 0 8
2023-07-02T08:01:53.136108+00:00 app[worker.1]: ERROR:chess.engine:Exception parsing pv from info: 'depth 15 seldepth 32 multipv 1 score cp -966 nodes 93786 nps 3126200 hashfull 6 tbhits 0 time 30 pv c7d6 b5d6 e8d7 d4e5 e7g6 d1d5 f8d6 e5d6 d7e8 f3g5 g6e5 f2f4 h7h6 d6d7 c8d7 g5e4 d7e6 d5b5 e8f8 f4e5 a8c8 b5b7 c6e5', position at root: r1bpkb1r/ppp1nppp/2n5/1N1pp3/3P4/5N2/PP2PPPP/R1BQKB1R w KQkq - 0 8
2023-07-02T08:01:53.141675+00:00 app[worker.1]: ERROR:chess.engine:Exception parsing pv from info: 'depth 16 seldepth 24 multipv 1 score cp -966 nodes 115429 nps 3206361 hashfull 6 tbhits 0 time 36 pv c7d6 b5d6 e8d7 d4e5 e7g6 d1d5 f8d6 e5d6 d7e8 f3g5 g6e5 f2f4 h7h6 d6d7 c8d7 g5e4 d7e6 d5b5 e8f8 f4e5 a8c8 b5b7 c6e5 e4d6', position at root: r1bpkb1r/ppp1nppp/2n5/1N1pp3/3P4/5N2/PP2PPPP/R1BQKB1R w KQkq - 0 8
2023-07-02T08:01:53.183356+00:00 app[worker.1]: ERROR:chess.engine:Exception parsing pv from info: 'depth 17 seldepth 30 multipv 1 score cp -969 nodes 279027 nps 3623727 hashfull 15 tbhits 0 time 77 pv c7d6 b5d6 e8d7 d4e5 e7g6 d6f7 f8b4 c1d2 h8f8 e5e6 d7e7 d2b4 c6b4 a1c1 b4c6 d1b3 c8e6 b3b7 e6d7 f3g5 g6e5 f7e5 c6e5 b7d5 e5d3 d5d3 f8c8', position at root: r1bpkb1r/ppp1nppp/2n5/1N1pp3/3P4/5N2/PP2PPPP/R1BQKB1R w KQkq - 0 8
2023-07-02T08:01:53.295710+00:00 app[worker.1]: ERROR:chess.engine:Exception parsing pv from info: 'depth 18 seldepth 41 multipv 1 score cp -970 nodes 673730 nps 3545947 hashfull 34 tbhits 0 time 190 pv c7d6 b5d6 e8d7 d4e5 e7g6 d6f7 f8b4 c1d2 h8f8 e5e6 d7e7 d2b4 c6b4 a1c1 b4c6 d1b3 h7h6 e2e4 f8f7 e6f7 e7f7 e4d5 c6e5 f3d4 c8d7 b3b7 a8e8 f1a6', position at root: r1bpkb1r/ppp1nppp/2n5/1N1pp3/3P4/5N2/PP2PPPP/R1BQKB1R w KQkq - 0 8
2023-07-02T08:01:53.361167+00:00 app[worker.1]: ERROR:chess.engine:Exception parsing pv from info: 'depth 19 seldepth 31 multipv 1 score cp -975 nodes 914151 nps 3584905 hashfull 46 tbhits 0 time 255 pv c7d6 b5d6 e8d7 d4e5 e7g6 d6f7 f8b4 c1d2 h8f8 e5e6 d7e7 d2b4 c6b4 a1c1 b4c6 d1b3 h7h6 e2e4 f8f7 e6f7 e7f7 c1c2 c8d7 b3b7', position at root: r1bpkb1r/ppp1nppp/2n5/1N1pp3/3P4/5N2/PP2PPPP/R1BQKB1R w KQkq - 0 8
2023-07-02T08:01:53.654879+00:00 app[worker.1]: ERROR:chess.engine:Exception parsing pv from info: 'depth 20 seldepth 36 multipv 1 score cp -970 nodes 1856818 nps 3382182 hashfull 105 tbhits 0 time 549 pv c7d6 b5d6 e8d7 d4e5 e7g6 d1d5 f8d6 e5d6 d7e8 b2b4 a7a6 h2h4 h7h5 f3g5 g6e5 f2f4 c8e6 g5e6 e5d3 e2d3 f7e6 d5e4', position at root: r1bpkb1r/ppp1nppp/2n5/1N1pp3/3P4/5N2/PP2PPPP/R1BQKB1R w KQkq - 0 8
2023-07-02T08:01:53.897820+00:00 app[worker.1]: ERROR:chess.engine:Exception parsing pv from info: 'depth 21 seldepth 34 multipv 1 score cp -979 nodes 2760771 nps 3485821 hashfull 154 tbhits 0 time 792 pv c7d6 b5d6 e8d7 d4e5 e7g6 d1d5 f8d6 e5d6 d7e8 b2b4 c8e6 d5e4 a7a6 h2h4 h7h5 f3g5 g6e5 c1b2 e8f8 f2f4 e5g4 g5e6 f7e6 e4e6 h8h6 e6d7 g4f6 d7b7 a8b8 b7c6 b8b4 c6a8 f8f7 e1c1 b4f4', position at root: r1bpkb1r/ppp1nppp/2n5/1N1pp3/3P4/5N2/PP2PPPP/R1BQKB1R w KQkq - 0 8
2023-07-02T08:01:54.446866+00:00 app[worker.1]: ERROR:chess.engine:Exception parsing pv from info: 'depth 22 seldepth 36 multipv 1 score cp -979 nodes 4394121 nps 3276749 hashfull 250 tbhits 0 time 1341 pv c7d6 b5d6 e8d7 d4e5 e7g6 d1d5 f8d6 e5d6 d7e8 b2b4 a7a6 h2h4 c8e6 d5e4 h7h5 f3g5 g6e5 c1b2 e8f8 b4b5 a6b5 b2e5 c6e5 e4e5 h8h6 a1d1 a8d8 d6d7 d8d7', position at root: r1bpkb1r/ppp1nppp/2n5/1N1pp3/3P4/5N2/PP2PPPP/R1BQKB1R w KQkq - 0 8
2023-07-02T08:01:54.447161+00:00 app[worker.1]: Exception in thread Thread-4:
2023-07-02T08:01:54.447164+00:00 app[worker.1]: Traceback (most recent call last):
2023-07-02T08:01:54.447187+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/chess/engine.py", line 1858, in _parse_uci_bestmove
2023-07-02T08:01:54.447957+00:00 app[worker.1]:     move = board.push_uci(tokens[0].lower())
2023-07-02T08:01:54.447958+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/chess/__init__.py", line 3136, in push_uci
2023-07-02T08:01:54.448343+00:00 app[worker.1]:     move = self.parse_uci(uci)
2023-07-02T08:01:54.448343+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/chess/__init__.py", line 3120, in parse_uci
2023-07-02T08:01:54.448668+00:00 app[worker.1]:     raise IllegalMoveError(f"illegal uci: {uci!r} in {self.fen()}")
2023-07-02T08:01:54.448682+00:00 app[worker.1]: chess.IllegalMoveError: illegal uci: 'c7d6' in r1bpkb1r/ppp1nppp/2n5/1N1pp3/3P4/5N2/PP2PPPP/R1BQKB1R w KQkq - 0 8
2023-07-02T08:01:54.448682+00:00 app[worker.1]: 
2023-07-02T08:01:54.448683+00:00 app[worker.1]: During handling of the above exception, another exception occurred:
2023-07-02T08:01:54.448683+00:00 app[worker.1]: 
2023-07-02T08:01:54.448683+00:00 app[worker.1]: Traceback (most recent call last):
2023-07-02T08:01:54.448684+00:00 app[worker.1]:   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
2023-07-02T08:01:54.448818+00:00 app[worker.1]:     self.run()
2023-07-02T08:01:54.448819+00:00 app[worker.1]:   File "/game.py", line 72, in run
2023-07-02T08:01:54.448864+00:00 app[worker.1]:     self._make_move()
2023-07-02T08:01:54.448864+00:00 app[worker.1]:   File "/game.py", line 99, in _make_move
2023-07-02T08:01:54.448901+00:00 app[worker.1]:     uci_move, offer_draw, resign = self.lichess_game.make_move()
2023-07-02T08:01:54.448902+00:00 app[worker.1]:   File "/lichess_game.py", line 81, in make_move
2023-07-02T08:01:54.448936+00:00 app[worker.1]:     move, info = self._make_engine_move()
2023-07-02T08:01:54.448936+00:00 app[worker.1]:   File "/lichess_game.py", line 599, in _make_engine_move
2023-07-02T08:01:54.449020+00:00 app[worker.1]:     result = self.engine.play(self.board, limit, info=chess.engine.INFO_ALL, ponder=ponder)
2023-07-02T08:01:54.449021+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/chess/engine.py", line 2795, in play
2023-07-02T08:01:54.449316+00:00 app[worker.1]:     return future.result()
2023-07-02T08:01:54.449317+00:00 app[worker.1]:   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
2023-07-02T08:01:54.449389+00:00 app[worker.1]:     return self.__get_result()
2023-07-02T08:01:54.449389+00:00 app[worker.1]:   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
2023-07-02T08:01:54.449447+00:00 app[worker.1]:     raise self._exception
2023-07-02T08:01:54.449448+00:00 app[worker.1]:   File "/usr/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
2023-07-02T08:01:54.449514+00:00 app[worker.1]:     return await fut
2023-07-02T08:01:54.449514+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/chess/engine.py", line 1685, in play
2023-07-02T08:01:54.449694+00:00 app[worker.1]:     return await self.communicate(UciPlayCommand)
2023-07-02T08:01:54.449695+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/chess/engine.py", line 1094, in communicate
2023-07-02T08:01:54.449816+00:00 app[worker.1]:     return await command.result
2023-07-02T08:01:54.449817+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/chess/engine.py", line 1305, in _line_received
2023-07-02T08:01:54.449951+00:00 app[worker.1]:     self.line_received(engine, line)
2023-07-02T08:01:54.449951+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/chess/engine.py", line 1622, in line_received
2023-07-02T08:01:54.450116+00:00 app[worker.1]:     self._bestmove(engine, line.split(" ", 1)[1])
2023-07-02T08:01:54.450116+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/chess/engine.py", line 1641, in _bestmove
2023-07-02T08:01:54.450279+00:00 app[worker.1]:     best = _parse_uci_bestmove(engine.board, arg)
2023-07-02T08:01:54.450279+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/chess/engine.py", line 1860, in _parse_uci_bestmove
2023-07-02T08:01:54.450479+00:00 app[worker.1]:     raise EngineError(err)
2023-07-02T08:01:54.450479+00:00 app[worker.1]: chess.engine.EngineError: illegal uci: 'c7d6' in r1bpkb1r/ppp1nppp/2n5/1N1pp3/3P4/5N2/PP2PPPP/R1BQKB1R w KQkq - 0 8
```

I am wondering if thats a hash-missing error or something else ?
Thanks

**Comment by Torom** [comment]
Engine error, no BotLi error.
`c7d6` is not a legal move in `r1bpkb1r/ppp1nppp/2n5/1N1pp3/3P4/5N2/PP2PPPP/R1BQKB1R w KQkq - 0 8`
