### ISSUE TITLE
Matchmaking issue

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#138]
Hi, when I was trying to do matchmaking, this occured
```
2023-09-10T06:21 ▶ DEFAULT  ▶ Exception in thread Thread-1:

2023-09-10T06:21 ▶ DEFAULT  ▶ Traceback (most recent call last):

2023-09-10T06:21 ▶ DEFAULT  ▶   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner

2023-09-10T06:21 ▶ DEFAULT  ▶     self.run()

2023-09-10T06:21 ▶ DEFAULT  ▶   File "/game_manager.py", line 50, in run

2023-09-10T06:21 ▶ DEFAULT  ▶     self._check_for_finished_games()

2023-09-10T06:21 ▶ DEFAULT  ▶   File "/game_manager.py", line 112, in _check_for_finished_games

2023-09-10T06:21 ▶ DEFAULT  ▶     self.matchmaking.on_game_finished(game)

2023-09-10T06:21 ▶ DEFAULT  ▶   File "/matchmaking.py", line 79, in on_game_finished

2023-09-10T06:21 ▶ DEFAULT  ▶     self.opponents.add_timeout(not was_aborted, game_duration)

2023-09-10T06:21 ▶ DEFAULT  ▶   File "/opponents.py", line 117, in add_timeout

2023-09-10T06:21 ▶ DEFAULT  ▶     self._save()

2023-09-10T06:21 ▶ DEFAULT  ▶   File "/opponents.py", line 150, in _save

2023-09-10T06:21 ▶ DEFAULT  ▶     with open(self.matchmaking_file, 'w', encoding='utf-8') as json_output:

2023-09-10T06:21 ▶ DEFAULT  ▶ PermissionError: [Errno 13] Permission denied: 'FireFishBOT_matchmaking.json'
```

**Comment by Torom** [comment]
Wherever you try to run BotLi you have no write permissions. And BotLi creates a matchmaking file during matchmaking and wants to write it, this is not possible without write permissions.
