### ISSUE TITLE
Use BOTli on another site

### ISSUE THREAD

**Issue by tititogepi** [Torom/BotLi#139]
Hi! Is it possible to use BotLi on another site like playstrategy.org ? Ist is possible to change eg url or other things in order to have the ability to use it on PlayStrategy?

**Comment by Torom** [comment]
No. Currently the URL of lichess is hardcoded. But I should change that sometime.

If the API of PlayStrategy is compatible to the one of lichess, BotLi would theoretically work there too. But I have not dealt with any other site than lichess.

**Comment by tititogepi** [comment]
Okay, so if i'd change that myself with a fork of your repository, which files must I change?
And yes, PlayStrategy's API is compatible to Lichess' APi :)

**Comment by Torom** [comment]
Only api.py I guess

**Comment by Torom** [comment]
But I'll make the URL configurable soon.

**Comment by Torom** [comment]
Now that I think about it, BotLi will probably crash if you try to play variants that are not also supported on Lichess.

Also [python-chess](https://python-chess.readthedocs.io/en/latest/variant.html), the library BotLi uses for pretty much everything, only supports the Lichess variants if I see it correctly.

**Comment by tititogepi** [comment]
Oh okay but as there are many games but also lichess variants on PlayStrategy, we could use it at least for it

**Comment by Torom** [comment]
Since 2c7b968 you can set the URL in the config.yml. Please give feedback how good this works.

**Comment by tititogepi** [comment]
Thx! Where should I write the URL on the config file?

**Comment by Torom** [comment]
Simply somewhere top level:

```yaml
url: "https://playstrategy.org"
```

**Comment by tititogepi** [comment]
Okay thank you very much I'll test it today :)

**Comment by tititogepi** [comment]
I've got this error : 

Traceback (most recent call last):
  File "C:\Users\emman\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emman\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emman\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emman\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\emman\Documents\ttBOT\Echecs\BOT\PSBOT\BOT\user_interface.py", line 316, in <module>
    ui.main()
  File "C:\Users\emman\Documents\ttBOT\Echecs\BOT\PSBOT\BOT\user_interface.py", line 53, in main
    self._handle_bot_status()
  File "C:\Users\emman\Documents\ttBOT\Echecs\BOT\PSBOT\BOT\user_interface.py", line 102, in _handle_bot_status
    if 'bot:play' not in self.api.get_token_scopes(self.config['token']):
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emman\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emman\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emman\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "C:\Users\emman\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emman\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\emman\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emman\Documents\ttBOT\Echecs\BOT\PSBOT\BOT\api.py", line 168, in get_token_scopes
    return response.json()[token]['scopes']
           ^^^^^^^^^^^^^^^
  File "C:\Users\emman\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Torom** [comment]
It looks like they are missing this endpoint: https://lichess.org/api#tag/OAuth/operation/tokenTest

**Comment by tititogepi** [comment]
Oh yes PlayStrategy tokens are old lichess tokens : it doesn't comport the suffix "lip"....

**Comment by Torom** [comment]
That alone would not be a problem. But the API is too old. It simply lacks endpoints that BotLi needs to work correctly.

**Comment by tititogepi** [comment]
Oh okay...

**Comment by M-DinhHoangViet** [comment]
playstrategy not have API Bots online
