### ISSUE TITLE
Not Working properly on Heroku

### ISSUE THREAD

**Issue by RoboTicCoders** [Torom/BotLi#24]
I have been using botli yesterday and in the logs it shows 
2022-07-12T01:48:23.480452+00:00 heroku[worker.1]: Process running mem=635M(124.1%)
2022-07-12T01:48:23.486168+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
And another issue is i have created my own book and i have uploaded to engines in my fork and when i start the dynos it takes a really long time and Bot immediately stops after using the book.My problem is without a book its ok but when i use my book engine automatically stops.How to fix this issue???

**Comment by Torom** [comment]
You fixed it yourself?
`Memory quota exceeded` means that you are using too much memory for Heroku, reduce the hash of the engine to get rid of the warning.

It sounds like there are problems with the book. Is there anything in the logs when BotLi stops playing?

**Comment by Torom** [comment]
However, your deployment to Heroku is not working anymore since a few commits. [Dockerfile#L17](https://github.com/RoboTicCoders/BotLi/blob/3d0c72734dcc603c2fa5d35776b912cc3d2bb1f2/Dockerfile#L17) breaks your Dockerfile. It is a duplicate of line 9 and results in an error. As it says in your [GitHub Actions](https://github.com/RoboTicCoders/BotLi/actions) every time.

**Comment by RoboTicCoders** [comment]
thanks torom it worked!!!!!!!!

**Comment by RoboTicCoders** [comment]
thank you for your time

**Comment by RoboTicCoders** [comment]
here 
2022-07-12T07:57:15.143290+00:00 app[worker.1]: Traceback (most recent call last):
2022-07-12T07:57:15.143306+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 489, in send
2022-07-12T07:57:15.143544+00:00 app[worker.1]:     resp = conn.urlopen(
2022-07-12T07:57:15.143568+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
2022-07-12T07:57:15.143862+00:00 app[worker.1]:     retries = retries.increment(
2022-07-12T07:57:15.143887+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 550, in increment
2022-07-12T07:57:15.144130+00:00 app[worker.1]:     raise six.reraise(type(error), error, _stacktrace)
2022-07-12T07:57:15.144153+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/urllib3/packages/six.py", line 769, in reraise
2022-07-12T07:57:15.144459+00:00 app[worker.1]:     raise value.with_traceback(tb)
2022-07-12T07:57:15.144482+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
2022-07-12T07:57:15.144756+00:00 app[worker.1]:     httplib_response = self._make_request(
2022-07-12T07:57:15.144779+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 449, in _make_request
2022-07-12T07:57:15.145001+00:00 app[worker.1]:     six.raise_from(e, None)
2022-07-12T07:57:15.145024+00:00 app[worker.1]:   File "<string>", line 3, in raise_from
2022-07-12T07:57:15.145136+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 444, in _make_request
2022-07-12T07:57:15.145341+00:00 app[worker.1]:     httplib_response = conn.getresponse()
2022-07-12T07:57:15.145363+00:00 app[worker.1]:   File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse
2022-07-12T07:57:15.145845+00:00 app[worker.1]:     response.begin()
2022-07-12T07:57:15.145869+00:00 app[worker.1]:   File "/usr/lib/python3.10/http/client.py", line 318, in begin
2022-07-12T07:57:15.146114+00:00 app[worker.1]:     version, status, reason = self._read_status()
2022-07-12T07:57:15.146137+00:00 app[worker.1]:   File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
2022-07-12T07:57:15.146373+00:00 app[worker.1]:     raise RemoteDisconnected("Remote end closed connection without"
2022-07-12T07:57:15.146411+00:00 app[worker.1]: urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-07-12T07:57:15.146430+00:00 app[worker.1]: 
2022-07-12T07:57:15.146430+00:00 app[worker.1]: During handling of the above exception, another exception occurred:
2022-07-12T07:57:15.146431+00:00 app[worker.1]: 
2022-07-12T07:57:15.146449+00:00 app[worker.1]: Traceback (most recent call last):
2022-07-12T07:57:15.146469+00:00 app[worker.1]:   File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
2022-07-12T07:57:15.146805+00:00 app[worker.1]:     self.run()
2022-07-12T07:57:15.146828+00:00 app[worker.1]:   File "/game.py", line 79, in run
2022-07-12T07:57:15.146956+00:00 app[worker.1]:     self.api.send_chat_message(self.game_id, chat_message.room, response)
2022-07-12T07:57:15.146978+00:00 app[worker.1]:   File "/api.py", line 145, in send_chat_message
2022-07-12T07:57:15.147113+00:00 app[worker.1]:     response = self.session.post(
2022-07-12T07:57:15.147134+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 635, in post
2022-07-12T07:57:15.147389+00:00 app[worker.1]:     return self.request("POST", url, data=data, json=json, **kwargs)
2022-07-12T07:57:15.147412+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 587, in request
2022-07-12T07:57:15.147677+00:00 app[worker.1]:     resp = self.send(prep, **send_kwargs)
2022-07-12T07:57:15.147701+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 701, in send
2022-07-12T07:57:15.147979+00:00 app[worker.1]:     r = adapter.send(request, **kwargs)
2022-07-12T07:57:15.148002+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 547, in send
2022-07-12T07:57:15.148240+00:00 app[worker.1]:     raise ConnectionError(err, request=request)
2022-07-12T07:57:15.148275+00:00 app[worker.1]: requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by RoboTicCoders** [comment]
the error

**Comment by Torom** [comment]
Not sure what happened there. For some reason the connection to Lichess broke. Does this happen frequently?

**Comment by RoboTicCoders** [comment]
yes

**Comment by RoboTicCoders** [comment]
k
