### ISSUE TITLE
Run at a same time

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#34]
How can I run stockfish and fairy-stockfish at a same time? Is it possible? Thanks 
I tried to edit the Dockerfile

**Comment by Torom** [comment]
First of all, you have not set your app name, that's why the deployment fails: [.github/workflows/main.yml#L17](https://github.com/FatFritz2/BotLi/blob/ba130fde01e80f05dd685ec48950313b7d3821d7/.github/workflows/main.yml#L17)

Secondly, you can't just enable the variant engine. It is not downloaded in the Dockerfile by default. You need to adjust your Dockerfile for that.

You could add something like this to the Dockerfile:

```Dockerfile
RUN wget https://github.com/ianfab/Fairy-Stockfish/releases/download/fairy_sf_14/fairy-stockfish_x86-64-bmi2
RUN mv fairy-stockfish_x86-64-bmi2 engines/fairy-stockfish && chmod +x engines/fairy-stockfish
```

**Comment by FatFritz2** [comment]
2022-07-31T08:49:44.908608+00:00 heroku[worker.1]: State changed from crashed to starting
2022-07-31T08:49:52.947892+00:00 heroku[worker.1]: Starting process with command `/bin/sh -c python3\ user_interface.py\ --non_interactive`
2022-07-31T08:49:54.073864+00:00 app[worker.1]: There appears to be a syntax problem with your config.yml
2022-07-31T08:49:54.073954+00:00 app[worker.1]: Traceback (most recent call last):
2022-07-31T08:49:54.073971+00:00 app[worker.1]:   File "//user_interface.py", line 183, in <module>
2022-07-31T08:49:54.074126+00:00 app[worker.1]:     ui = UserInterface()
2022-07-31T08:49:54.074141+00:00 app[worker.1]:   File "//user_interface.py", line 23, in __init__
2022-07-31T08:49:54.074221+00:00 app[worker.1]:     self.config = load_config()
2022-07-31T08:49:54.074235+00:00 app[worker.1]:   File "/config.py", line 14, in load_config
2022-07-31T08:49:54.074306+00:00 app[worker.1]:     raise e
2022-07-31T08:49:54.074319+00:00 app[worker.1]:   File "/config.py", line 11, in load_config
2022-07-31T08:49:54.074390+00:00 app[worker.1]:     CONFIG = yaml.safe_load(stream)
2022-07-31T08:49:54.074404+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/yaml/__init__.py", line 125, in safe_load
2022-07-31T08:49:54.074499+00:00 app[worker.1]:     return load(stream, SafeLoader)
2022-07-31T08:49:54.074511+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/yaml/__init__.py", line 81, in load
2022-07-31T08:49:54.074593+00:00 app[worker.1]:     return loader.get_single_data()
2022-07-31T08:49:54.074607+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/yaml/constructor.py", line 49, in get_single_data
2022-07-31T08:49:54.074681+00:00 app[worker.1]:     node = self.get_single_node()
2022-07-31T08:49:54.074695+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 36, in get_single_node
2022-07-31T08:49:54.074772+00:00 app[worker.1]:     document = self.compose_document()
2022-07-31T08:49:54.074785+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 55, in compose_document
2022-07-31T08:49:54.074858+00:00 app[worker.1]:     node = self.compose_node(None, None)
2022-07-31T08:49:54.074872+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 84, in compose_node
2022-07-31T08:49:54.074977+00:00 app[worker.1]:     node = self.compose_mapping_node(anchor)
2022-07-31T08:49:54.074991+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
2022-07-31T08:49:54.075077+00:00 app[worker.1]:     item_value = self.compose_node(node, item_key)
2022-07-31T08:49:54.075090+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 84, in compose_node
2022-07-31T08:49:54.075171+00:00 app[worker.1]:     node = self.compose_mapping_node(anchor)
2022-07-31T08:49:54.075184+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
2022-07-31T08:49:54.075273+00:00 app[worker.1]:     item_value = self.compose_node(node, item_key)
2022-07-31T08:49:54.075287+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 84, in compose_node
2022-07-31T08:49:54.075367+00:00 app[worker.1]:     node = self.compose_mapping_node(anchor)
2022-07-31T08:49:54.075380+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
2022-07-31T08:49:54.075469+00:00 app[worker.1]:     while not self.check_event(MappingEndEvent):
2022-07-31T08:49:54.075482+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/yaml/parser.py", line 98, in check_event
2022-07-31T08:49:54.075612+00:00 app[worker.1]:     self.current_event = self.state()
2022-07-31T08:49:54.075625+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/yaml/parser.py", line 438, in parse_block_mapping_key
2022-07-31T08:49:54.075823+00:00 app[worker.1]:     raise ParserError("while parsing a block mapping", self.marks[-1],
2022-07-31T08:49:54.075860+00:00 app[worker.1]: yaml.parser.ParserError: while parsing a block mapping
2022-07-31T08:49:54.075860+00:00 app[worker.1]:   in "config.yml", line 39, column 5
2022-07-31T08:49:54.075860+00:00 app[worker.1]: expected <block end>, but found '<block mapping start>'
Idk what happened

**Comment by Torom** [comment]
`2022-07-31T08:49:54.073864+00:00 app[worker.1]: There appears to be a syntax problem with your config.yml`

You broke the indentations in your config in several places in [this](https://github.com/FatFritz2/BotLi/commit/4582fbca1501dcaea4d064c63b9759544d9a291c) commit. This can help you check the syntax: https://jsonformatter.org/yaml-validator

**Comment by FatFritz2** [comment]
Error : bad indentation of a mapping entry at line 45, column 6:
         max_depth: 20                    ... 
         ^
Line : undefined  undefined

**Comment by Torom** [comment]
Right, that's one of the lines.

**Comment by FatFritz2** [comment]
SO how do I correct it

**Comment by FatFritz2** [comment]
Anyway, here's my config.yml:
token: "lip_51keV0Gz9Xwyol0mMYpA"         # Lichess OAuth2 Token.

engine:                                   # Engine settings.
  dir: "./engines"                        # Directory containing the engine.
  name: "stockfish"                       # Binary name of the engine to use.
  ponder: true                            # Think on opponent's time.
  uci_options:                            # Arbitrary UCI options passed to the engine. (Commenting allowed)
    Move Overhead: 100                    # Increase if your bot flags games too often.
    Threads: 10                           # Max CPU threads the engine can use.
    Hash: 256                             # Max memory (in megabytes) the engine can allocate.
#   SyzygyPath: "/path/to/syzygy"         # Path to your local syzygy endgame tablebases
  variants:
    enabled: true                         # Activate seperate engine for other chess variants than standard and chess960.
    dir: "./engines"                      # Directory containing the engine.
    name: "fairy-stockfish"               # Binary name of the engine to use.
    uci_options:                          # Arbitrary UCI options passed to the engine. (Commenting allowed)
      Move Overhead: 100                  # Increase if your bot flags games too often.
      Threads: 10                         # Max CPU threads the engine can use.
      Hash: 256                           # Max memory (in megabytes) the engine can allocate.
  opening_books:
    enabled: true                         # Activate opening books.
    books:
#     white:                              # List of names of books to use as white.
#       - "WhiteBook"
#     black:                              # List of names of books to use as black.
#       - "BlackBook"
      standard:                           # List of names of books to use if there is no specific book for white, black or chess960.
        - "bestbook.bin"
        - "Perfect2021.bin"
        - "Drawkiller_EloZoom_big.bin"
        - "tcec.bin"
        - "komodo.bin"
#     chess960:                           # List of names of books to use for chess960.
#       - "Chess960Book"
#     Use the same pattern for 'antichess', 'atomic', 'crazyhouse', 'horde', 'kingofthehill', 'racingkings' and '3check' as well.
    selection: "weighted_random"          # Move selection is one of "weighted_random", "uniform_random" or "best_move".
    max_depth: 50                         # Half move max depth. (Comment this line for max depth)
  online_moves:
    chessdb:
      enabled: true                       # Activate online moves from https://chessdb.cn/queryc_en/
      min_eval_depth: 10                  # Minimum evaluation depth. Only for selection: "best".
      min_time: 30                        # Time the bot must have at least to use the online move.
      timeout: 5                          # Time the server has to respond.
      selection: "best"                   # Move selection is one of "best", "good" or "all".
     max_depth: 20                        # Half move max depth. (Comment this line for max depth)
    lichess_cloud:
      enabled: true                       # Activate online moves from Lichess cloud eval.
      min_eval_depth: 10                  # Minimum evaluation depth.
      min_time: 30                        # Time the bot must have at least to use the online move.
      timeout: 5                          # Time the server has to respond.
     max_depth: 20                        # Half move max depth. (Comment this line for max depth)
    online_egtb:
      enabled: true                       # Activate online endgame tablebases from Lichess.
      min_time: 5                         # Time the bot must have at least to use the online move.
      timeout: 3                          # Time the server has to respond.
  offer_draw:
    enabled: true                         # Activate whether the bot should offer draw.
    score: 10                             # If the absolute value of the score is less than or equal to this value, the bot offers/accepts draw (in cp)
    consecutive_moves: 10                 # How many moves in a row the absolute value of the score has to be below the draw value
    min_game_length: 35                   # Earliest move in which draw is offered.
  resign:
    enabled: false                        # Activate whether the bot should resign games.
    score: -1000                          # If the score is less than or equal to this value, the bot resigns (in cp).
    consecutive_moves: 5                  # How many moves in a row the score has to be below the resign value.

move_overhead_multiplier: 1.0             # Increase if your bot flags games too often. Default move overhead is 1 second per 1 minute initital time.
    
challenge:                                # Incoming challenges. (Commenting allowed)
  concurrency: 1                          # Number of games to play simultaneously.
  bullet_with_increment_only: false       # Whether bullet games should be accepted with increment only.
 min_increment: 1                         # Minimum amount of increment to accept a challenge.
  max_increment: 180                      # Maximum amount of increment to accept a challenge.
  min_initial: 5                          # Minimum amount of initial time to accept a challenge.
  max_initial: 315360000                  # Maximum amount of initial time to accept a challenge.
  variants:                               # Chess variants to accept (https://lichess.org/variant).
    - standard
    - chess960
#   - fromPosition
    - antichess
    - atomic
    - crazyhouse
    - horde
    - kingOfTheHill
    - racingKings
    - threeCheck
  time_controls:                          # Time controls to accept.
    - bullet
    - blitz
    - rapid
    - classical
  bot_modes:                              # Game modes to accept against BOTs.
    - casual                              # Unrated games.
    - rated                               # Rated games
  human_modes:                            # Game modes to accept against humans.
    - casual                              # Unrated games.
    - rated                               # Rated games

matchmaking:
  initial_time: 60                        # Initial time for matchmaking mode.
  increment: 1                            # Increment time for matchmaking mode.
  rated: true                             # Activate rated games in matchmaking mode.
  timeout: 60                             # Time until a challenge is canceled.
  variant: standard                       # Chess variant (https://lichess.org/variant) to challenge.
  min_rating_diff: 0                      # Minimum rating distance to opponent. (Commenting allowed)
  max_rating_diff: 300                    # Maximum rating distance to opponent. (Commenting allowed)
  delay: 10                               # Time in seconds the bot must be idle before a new challenge is started.

books:                                    # Names of the opening books (to be used above in the opening_books section) and paths to the opening books.
  bestbook.bin: "bestbook.bin"
  Perfect2021.bin: "Perfect2021.bin"
  Drawkiller_EloZoom_big.bin: "Drawkiller_EloZoom_big.bin"
  tcec.bin: "tcec.bin"
  komodo.bin: "komodo.bin"

**Comment by Torom** [comment]
Fix the indentation in lines 45, 51, and 71. A whitespace is missing in each.

**Comment by FatFritz2** [comment]
Thanks

**Comment by FatFritz2** [comment]
Oh thanks

**Comment by FatFritz2** [comment]
it worked thanks
