### ISSUE TITLE
Horde variant

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#40]
This happened when I started to play a horde game:
2022-08-06T14:44:15.446393+00:00 app[worker.1]: Exception in thread Thread-4:
2022-08-06T14:44:15.446425+00:00 app[worker.1]: Traceback (most recent call last):
2022-08-06T14:44:15.446456+00:00 app[worker.1]:   File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
2022-08-06T14:44:15.446727+00:00 app[worker.1]:     self.run()
2022-08-06T14:44:15.446735+00:00 app[worker.1]:   File "/game.py", line 42, in run
2022-08-06T14:44:15.446796+00:00 app[worker.1]:     uci_move, offer_draw, resign = self.lichess_game.make_move()
2022-08-06T14:44:15.446806+00:00 app[worker.1]:   File "/lichess_game.py", line 62, in make_move
2022-08-06T14:44:15.446870+00:00 app[worker.1]:     move, info = self._make_engine_move()
2022-08-06T14:44:15.446872+00:00 app[worker.1]:   File "/lichess_game.py", line 338, in _make_engine_move
2022-08-06T14:44:15.446968+00:00 app[worker.1]:     result = self.engine.play(self.board, limit, info=chess.engine.INFO_ALL, ponder=ponder)
2022-08-06T14:44:15.446970+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/chess/engine.py", line 2781, in play
2022-08-06T14:44:15.447360+00:00 app[worker.1]:     return future.result()
2022-08-06T14:44:15.447362+00:00 app[worker.1]:   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 446, in result
2022-08-06T14:44:15.447464+00:00 app[worker.1]:     return self.__get_result()
2022-08-06T14:44:15.447466+00:00 app[worker.1]:   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
2022-08-06T14:44:15.447555+00:00 app[worker.1]:     raise self._exception
2022-08-06T14:44:15.447557+00:00 app[worker.1]:   File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
2022-08-06T14:44:15.447657+00:00 app[worker.1]:     return fut.result()
2022-08-06T14:44:15.447665+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/chess/engine.py", line 1671, in play
2022-08-06T14:44:15.447902+00:00 app[worker.1]:     return await self.communicate(UciPlayCommand)
2022-08-06T14:44:15.447905+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/chess/engine.py", line 1080, in communicate
2022-08-06T14:44:15.448071+00:00 app[worker.1]:     return await command.result
2022-08-06T14:44:15.448084+00:00 app[worker.1]: chess.engine.EngineTerminatedError: engine process died unexpectedly (exit code: 1)

**Comment by Torom** [comment]
Ah yes, the horde NNUE is not compatible with fairy-stockfish 14. Replace the fairy-stockfish download with:
```Dockerfile
RUN wget https://github.com/ianfab/Fairy-Stockfish/releases/download/fairy_sf_14_0_1_xq/fairy-stockfish-largeboard_x86-64-bmi2
RUN mv fairy-stockfish-largeboard_x86-64-bmi2 engines/fairy-stockfish && chmod +x engines/fairy-stockfish
```
