### ISSUE TITLE
Help config.yml

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#43]
Please look at my config.yml and see why I got this...
2022-08-13T02:53:15.595614+00:00 app[worker.1]: Exception in thread Thread-4:
2022-08-13T02:53:15.595627+00:00 app[worker.1]: Traceback (most recent call last):
2022-08-13T02:53:15.595628+00:00 app[worker.1]:   File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
2022-08-13T02:53:15.595977+00:00 app[worker.1]:     self.run()
2022-08-13T02:53:15.595988+00:00 app[worker.1]:   File "/game.py", line 58, in run
2022-08-13T02:53:15.596092+00:00 app[worker.1]:     uci_move, offer_draw, resign = self.lichess_game.make_move()
2022-08-13T02:53:15.596092+00:00 app[worker.1]:   File "/lichess_game.py", line 72, in make_move
2022-08-13T02:53:15.596170+00:00 app[worker.1]:     self.engine.analysis(self.board)
2022-08-13T02:53:15.596171+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/chess/engine.py", line 2798, in analysis
2022-08-13T02:53:15.596826+00:00 app[worker.1]:     with self._not_shut_down():
2022-08-13T02:53:15.596849+00:00 app[worker.1]:   File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
2022-08-13T02:53:15.596963+00:00 app[worker.1]:     return next(self.gen)
2022-08-13T02:53:15.596978+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/chess/engine.py", line 2740, in _not_shut_down
2022-08-13T02:53:15.597591+00:00 app[worker.1]:     raise EngineTerminatedError("engine event loop dead")
2022-08-13T02:53:15.597618+00:00 app[worker.1]: chess.engine.EngineTerminatedError: engine event loop dead

**Comment by Torom** [comment]
Your engine crashed for some reason. Not a BotLi issue.

**Comment by FatFritz2** [comment]
Oh I see
