### ISSUE TITLE
Something wrong with BotLi ?

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#48]
Book:    1...   Nf6
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\olymp\AppData\Roaming\Python\Python310\site-packages\chess\engine.py", line 1734, in analysis
    return await self.communicate(UciAnalysisCommand)
  File "C:\Users\olymp\AppData\Roaming\Python\Python310\site-packages\chess\engine.py", line 1080, in communicate
    return await command.result
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\asyncio\tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\olymp\Downloads\BotLi-main\game.py", line 44, in run
    uci_move, offer_draw, resign = self.lichess_game.make_move()
  File "C:\Users\olymp\Downloads\BotLi-main\lichess_game.py", line 70, in make_move
    self.engine.analysis(self.board)
  File "C:\Users\olymp\AppData\Roaming\Python\Python310\site-packages\chess\engine.py", line 2803, in analysis
    return SimpleAnalysisResult(self, future.result())
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Program Files\Python310\lib\asyncio\tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
Ye thats the thing I recieved in the terminal when trying to play with another bot

**Comment by Torom** [comment]
This is a problem with the engine. Which engine do you use and does the engine work independently from BotLi?

**Comment by FatFritz2** [comment]
Oh I see I got the wrong architecture of my engine ok it worked then
