### ISSUE TITLE
Um. help?

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#50]
File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\Downloads\BotLi-main\game.py", line 60, in run
    uci_move, offer_draw, resign = self.lichess_game.make_move()
  File "C:\Users\olymp\Downloads\BotLi-main\lichess_game.py", line 70, in make_move
    self.engine.analysis(self.board)
  File "C:\Users\AppData\Roaming\Python\Python310\site-packages\chess\engine.py", line 2803, in analysis
    return SimpleAnalysisResult(self, future.result())
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  AFile "C:\Program Files\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\Users\olymp\AppData\Roaming\Python\Python310\site-packages\chess\engine.py", line 1734, in analysis
    return await self.communicate(UciAnalysisCommand)
  File "C:\Users\AppData\Roaming\Python\Python310\site-packages\chess\engine.py", line 1080, in communicate
    return await command.result
chess.engine.EngineTerminatedError: engine process died unexpectedly (exit code: 1)

And...

  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\olymp\Downloads\BotLi-main\game.py", line 44, in run
    uci_move, offer_draw, resign = self.lichess_game.make_move()
  File "C:\Users\olymp\Downloads\BotLi-main\lichess_game.py", line 70, in make_move
    self.engine.analysis(self.board)
  File "C:\Users\olymp\AppData\Roaming\Python\Python310\site-packages\chess\engine.py", line 2803, in analysis
    return SimpleAnalysisResult(self, future.result())
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Program Files\Python310\lib\asyncio\tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
Exception in callback Protocol._line_received('readyok')
handle: <Handle Protocol._line_received('readyok')>
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\olymp\AppData\Roaming\Python\Python310\site-packages\chess\engine.py", line 1040, in _line_received
    self.command._line_received(self, line)
  File "C:\Users\olymp\AppData\Roaming\Python\Python310\site-packages\chess\engine.py", line 1291, in _line_received
    self.line_received(engine, line)
  File "C:\Users\olymp\AppData\Roaming\Python\Python310\site-packages\chess\engine.py", line 1702, in line_received
    self._readyok(engine)
  File "C:\Users\olymp\AppData\Roaming\Python\Python310\site-packages\chess\engine.py", line 1715, in _readyok
    self.result.set_result(self.analysis)
asyncio.exceptions.InvalidStateError: invalid state
No idea for that error :C

**Comment by Torom** [comment]
As always, these are engine errors. Test if the engine works independently from BotLi. No BotLi issues.
