### ISSUE TITLE
Variants error ?

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#52]
Hey @Torom I am having an error with fsf it looks like this...
2022-09-06T06:17:56.311180+00:00 app[worker.1]: Traceback (most recent call last):
2022-09-06T06:17:56.311202+00:00 app[worker.1]:   File "//user_interface.py", line 213, in <module>
2022-09-06T06:17:56.311306+00:00 app[worker.1]:     ui = UserInterface()
2022-09-06T06:17:56.311313+00:00 app[worker.1]:   File "//user_interface.py", line 24, in __init__
2022-09-06T06:17:56.311372+00:00 app[worker.1]:     self.config = load_config()
2022-09-06T06:17:56.311375+00:00 app[worker.1]:   File "/config.py", line 40, in load_config
2022-09-06T06:17:56.311434+00:00 app[worker.1]:     raise Exception(f'Your config.yml does not have required `engine` subsection `{subsection[0]}`.')
2022-09-06T06:17:56.311444+00:00 app[worker.1]: Exception: Your config.yml does not have required `engine` subsection `syzygy`.

**Comment by Torom** [comment]
`Your config.yml does not have required engine subsection syzygy.`
This is literally in the error message.

I have updated the default config yesterday. So you have to add the `syzygy` section to your config like [this](https://github.com/Torom/BotLi/blob/49ee62ca7a87e81d0757fc750fe6e60f0ca3b619/config.yml.default#L7-L12).

**Comment by FatFritz2** [comment]
So how can I add Syzygy for my bot on Heroku
And we have to add Syzygy, not Optional anymore ?

**Comment by Torom** [comment]
Of course, it is still optional. Just set `engine`: `syzygy`: `enabled` to `false` (default value) and everything is as before.

**Comment by FatFritz2** [comment]
Ok thanks got it 💯
