### ISSUE TITLE
Help me 🤙 

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#60]
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\olymp\Downloads\BotLi-main\game.py", line 63, in run
    uci_move, offer_draw, resign = self.lichess_game.make_move()
  File "C:\Users\olymp\Downloads\BotLi-main\lichess_game.py", line 54, in make_move
    elif response := self._make_opening_explorer_move():
  File "C:\Users\olymp\Downloads\BotLi-main\lichess_game.py", line 257, in _make_opening_explorer_move
    enabled = self.config['engine']['online_moves']['opening_explorer']['enabled']
KeyError: 'opening_explorer'

**Comment by Torom** [comment]
In 96ceeb3 I added the function to play moves from the Lichess opening explorer. You need to add these lines from the default config to your config: https://github.com/Torom/BotLi/blob/c738ae1d7ae6083184a14a34eeb72806dc652d4e/config.yml.default#L43-L50
