### ISSUE TITLE
No Idea ?

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#65]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\olymp\Downloads\BotLi-main\game.py", line 63, in run
    uci_move, offer_draw, resign = self.lichess_game.make_move()
  File "C:\Users\olymp\Downloads\BotLi-main\lichess_game.py", line 77, in make_move
    elif response := self._make_egtb_move():
  File "C:\Users\olymp\Downloads\BotLi-main\lichess_game.py", line 566, in _make_egtb_move
    if response := self.api.get_egtb(self.board.fen(), variant, timeout):
  File "C:\Users\olymp\Downloads\BotLi-main\api.py", line 109, in get_egtb
    response = self.session.get(
  File "C:\Users\olymp\AppData\Roaming\Python\Python310\site-packages\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\olymp\AppData\Roaming\Python\Python310\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\olymp\AppData\Roaming\Python\Python310\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\olymp\AppData\Roaming\Python\Python310\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='tablebase.lichess.ovh', port=443): Max retries exceeded with url: /standard?fen=8%2F8%2F6B1%2F6P1%2F1k6%2F1pp1b3%2F8%2F1K6+b+-+-+0+55 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001B8F22BB4F0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))

**Comment by Torom** [comment]
Some network problem. But this should not cause a crash, b1e4e3a catches the error.
