### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#70]
Do you have the same issue as mine ?

```
_Traceback (most recent call last):
  File "C:\Users\olymp\Downloads\BotLi-main2\user_interface.py", line 5, in <module>
    from api import API
  File "C:\Users\olymp\Downloads\BotLi-main2\api.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'_
```

**Comment by Torom** [comment]
You need to install the dependencies first:

```
python -m pip install -r requirements.txt
```

**Comment by FatFritz2** [comment]
Oh I see. I am having troubles because I have recently updated python to v3.11.1.
Thanks :D
