### ISSUE TITLE
Hmm do I need to install requirements here ?

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#72]
```
Starting matchmaking ...
handling challenges ...
Exception in thread Thread-4:
Traceback (most recent call last):
File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
self.run()
File "/game.py", line 43, in run
uci_move, offer_draw, resign = self.lichess_game.make_move()
File "/lichess_game.py", line 77, in make_move
self.engine.analysis(self.board)
File "/usr/local/lib/python3.10/dist-packages/chess/engine.py", line 2803, in analysis
return SimpleAnalysisResult(self, future.result())
File "/usr/lib/python3.10/concurrent/futures/_base.py", line 456, in result
raise CancelledError()
concurrent.futures._base.CancelledError
```

**Comment by Torom** [comment]
It's really not the first time you're trying to get help, you should know how to ask by now. If you don't stop posting commentless error messages and using the issues like your personal assistant, I will block you.
