### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by EmptikBest** [Torom/BotLi#92]
Yesterday, my bot (EmptikBot) was running completely fine. But today, when I started user_interface.py and put it on matchmaking mode, it gave me the following error:
`Exception in thread Thread-8:
Traceback (most recent call last):
  File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "F:\EmptikBot\game.py", line 35, in run
    self.lichess_game = Lichess_Game(self.api, self.game_info, self.config)
  File "F:\EmptikBot\lichess_game.py", line 42, in __init__
    self.engine = self._get_engine()
  File "F:\EmptikBot\lichess_game.py", line 710, in _get_engine
    engine = chess.engine.SimpleEngine.popen_uci(engine_path, stderr=stderr)
  File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 2861, in popen_uci
    return cls.popen(UciProtocol, command, timeout=timeout, debug=debug, setpgrp=setpgrp, **popen_args)
  File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 2853, in popen
    return run_in_background(background, name=f"{cls.__name__} (command={command!r})", debug=debug)
  File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 201, in run_in_background
    return future.result()
  File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 195, in background
    asyncio.run(coroutine(future))
  File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 2841, in background
    transport, protocol = await Protocol.popen(command, setpgrp=setpgrp, **popen_args)
  File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 1239, in popen
    return await asyncio.get_running_loop().subprocess_exec(cls, *command, **popen_args)
  File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1681, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 399, in _make_subprocess_transport
    transp = _WindowsSubprocessTransport(self, protocol, args, shell,
  File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\asyncio\base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 901, in _start
    self._proc = windows_utils.Popen(
  File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_utils.py", line 153, in __init__
    super().__init__(args, stdin=stdin_rfd, stdout=stdout_wfd,
  File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 216] This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher`

I am running Python 3.10 on Windows 10 Enterprise
Here is my config.yml with the token removed : https://drive.google.com/file/d/1pgcHKdTLM2qIFIdPbm3fMjQvF6sw14e6/view?usp=sharing

**Comment by EmptikBest** [comment]
Nevermind turns out it was a problem with my engine (Latest stockfish dev version)
Solved it by downgrading to another stockfish dev version
