### ISSUE TITLE
Any idea what this means?

### ISSUE THREAD

**Issue by EmptikBest** [Torom/BotLi#95]
Randomly in the middle of a game, the cmd got this message:
`ERROR:asyncio:Exception in callback Protocol._line_received('info depth 5...7f8 b2c3 f8e7')
handle: <Handle Protocol._line_received('info depth 5...7f8 b2c3 f8e7')>
Traceback (most recent call last):
  File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 1054, in _line_received
    self.command._line_received(self, line)
  File "C:\Users\Vinay Kumar\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 1303, in _line_received
    assert self.state in [CommandState.ACTIVE, CommandState.CANCELLING]
AssertionError`

After that, the game continued on normally. Any idea what this means?

**Comment by Torom** [comment]
A message from the python-chess library. Occasionally occurs for me, but seems to be harmless.

**Comment by EmptikBest** [comment]
Thanks
